### Site Settings ###
title               : Aji Setiawan
description         : >-
                      Seorang lulusan Program Studi Multimedia, Desainer Grafis, Webgrammer amatiran. 
                      Lihat proyek, portofolio, tulisan dan profilku di menu pojok kanan atas.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url                 : "https://www.ajisetiawan.my.id" #change to empty if you are'nt using github action 
repository          : ajisetiawan716/ajisetiawan716.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : ajisetiawan716/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)
breadcrumbs         : false # true, false (default)
img_cdn             : https://img-cdn.ajimedia.my.id
markdown: kramdown
sass:
    style: compressed
timezone: Asia/Jakarta
    
## Contact Form Settings ##
contact_form: https://formspree.io/f/mrgngpbk # Using Formspree.io backend
gsite_recaptcha: 6Ld690EpAAAAACGGrqDlNyzFKmjE7rTgQkhGT2QT

### Light Gallery Settings ###
lightgallery:
  enabled: true                                        # Set true to enable lightgalley
  
# Light Box Settings 
lightbox:
  enabled: false                                        # Set true to enable lightbox

# jekyll-related-posts settings.
related_by: tags and categories
related_limit: 6
related_categories: 1
related_tags: 1

### Plugins ### 
plugins:
  - jekyll-github-metadata 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-tagging-related_posts
  - mini_magick
  - jekyll-seo-tag

# Aditional Settings for mini_magick
thumbnail:
    resize_dimensions: '430x288^'
    crop_dimensions: '430x288+0+0'
    
### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md/**                           # For Documentation Only
  - pay/index.html/**
  - pay/turnitin.html
  - pay/thr.html
  - ig.html
  - wa.html
  - tg.html
  - resumes.html
  - donate.html
  - linkme.html
  - pages/portfolio.html
  - pages/download-ebook.html
  - pages/download-cv.html
  - pages/desain-cv.html
  - pages/comment-policy.md

### Author Info ###
author:
  name              : Aji Setiawan 
  image             : https://avatars.githubusercontent.com/u/106381048?v=4
  behance           : aji-setiawan
  dribbble          : ajisetiawan716
  email             : email@ajisetiawan.my.id
  facebook          : adjiee.setiawan
  github            : ajisetiawan716
# gitlab            : your_username
  instagram         : ajisetiawan716
# kaggle            : your_username
  linkedin          : ajisetiawan716
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : ajisetiawan716
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
  whatsapp          : 6281326482638
  telegram          : ajisetiawan716
  paypal            : ajisetiawan716
# Resume Settings
  resume:
    provider: "cvengineer" # false (default), "google", "cvengineer", "external"
    enabled: true                                        # Set true to enable analytics
    gdrive:
      link: https://drive.google.com/file/d/1JAnTh7Dq2r2VIFusGStRxr5IRuyZnBK3/preview      #change to your gdrive link pdf resume file
    cvengineer:
      username: ajisetiawan #change to your cvengineer username 
    external:
      link: 'https://your-cv.link/your-cv.pdf'
    custom:
      link: https://rxresu.me/ajisetiawan716/cv-aji
# Portfolio link Settings
  portfolio:
    provider: "gslide" # false (default), "gdrive", "external", "gslide"
    enabled: true                                        # Set true to enable analytics
    gdrive:
      link: https://drive.google.com/file/d/11HhbXkTWIaaMAdbjCkNtcrk1-FROPqgG/preview
    gslide:
      link: https://docs.google.com/presentation/d/e/2PACX-1vS0yyKjMRBDPazHfKgTpNKQt8Jgh0Bw4NZ08LyGn4dNhO6lrSvHqhIhc4T9Nm7mHCDYhKQydVhwKZev/embed
    external:
      link: https://www.ajisetiawan.my.id/assets/Portfolio-Aji-Setiawan.pdf

### Posts ###
permalink: /blog/:year/:month/:day/:title:output_ext
paginate: 4
paginate_path: "/blog/page-:num/"

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
 ### ADD SERVICE ###   
  service:
    output: true
    permalink: /services/:name
  ### END OF SERVICE ###  
  elements:                                             # For Documentation Only
    output: false                                        # For Documentation Only


### Disqus ## #comments:
comments:
  provider               : "false" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : "ajisetiawan" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
      
# SEO Related
google_site_verification : "YOUR_GOOGLE_SITE_CODE"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
keywords                 : portfolio, resume, aji setiawan, ajisetiawan716, ajisetiawan, python, HTML, CSS, design graphic, desain grafis, personal website, indonesia, indonesian, indonesia freelancers, freelancer

### Analytics ###
analytics:
  provider: "default" # false (default), "google", "google-universal", "custom"
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: G-238CT53NBG

### Google Adsense ###
tagmanager:
  enabled: true                                        # Set true to enable google Adsense
  google:
    tag_id: GTM-5BQ3JVM

### Google Translate ###
translate:
  enabled: true                                        # Set true to enable google translate

### AdBlock Detection ###
adblock_detect:
  enabled: true                                        # Set true to enable adblock detection

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"                                   # For Documentation Only
  ### SERVICE ADD ###
  - scope:
      path: ""
      type: "service"
    values:
      layout: "page"
  ### END OF SERVICE ADD ###    
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true # or false (default)
    # Posts defaults image
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts # Apply the default values below only to posts
    values:
      image: cover-default-image.png
      image-alt: Default Image Post
      
# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/img/content/cover-default-image.png"
    fb_image_width: 300
    fb_image_height: 300
    fb_image_type: "image/jpg"

    twitter_image: "/assets/img/content/cover-default-image.png"

    os_repo: "https://github.com/ajisetiawan716/ajisetiawan716.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:ajisetiawan716/ajisetiawan716.github.io"      

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - tmp/
  - vendor/
